### ISSUE TITLE
crypto.getRandomValues is not defined on Android

### ISSUE THREAD

**Issue by snikoletopoulos** [paulmillr/noble-ed25519#108]
On Android I get a `crypto.getRandomValues` is not defined error.
iOS seems to work fine.

The error started when I upgraded from 2.1.0 to 2.2.0.
With 2.1.0 everything is working fine.

As for the environment and setup
I am on the latest Expo SDK (52)
I have the `import "react-native-get-random-values";` before any call to `@noble` packages
And the polyfills are used

Dependencies versions:
`react-native-get-random-values`: 1.11.0
`@noble/hashes`: 1.7.0

**Comment by Jayydey** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Support Request](https://generalwebfixes.web.app/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by paulmillr** [comment]
I have no android, you will need to debug the issue yourself

**Comment by snikoletopoulos** [comment]
Can you give me some suggestions as to what might be wrong?

**Comment by paulmillr** [comment]
I think we have changed the logic lf checking if crypto exists. So, see how it works in 2.1 and diff with 2.2. Maybe it’s related to crypto.subtle

**Comment by paulmillr** [comment]
see if reverting https://github.com/paulmillr/noble-ed25519/commit/57c1d9e612fa5ffbd3ae0b7c43fc1e20ec748030 helps

**Comment by snikoletopoulos** [comment]
Can confirm after reverting this commit it works as expected again.
Turns out this error is on iOS as well. My bad.

`react-native-get-random-values` does not implement `crypto.subtle` so a polyfill for that is needed.

Alternatively, I see that there are checks in place where `crypto.subtle` is needed so maybe we can revert the checks in 57c1d9e. That we result in better error messages describing what is actually missing.

**Comment by paulmillr** [comment]
I assume you are using noble hashes to get sync methods?

**Comment by paulmillr** [comment]
fixed
